apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-portal-frontend
  namespace: learning-development
  labels:
    app: learning-portal-frontend
    cluster: learning-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-portal-frontend
  template:
    metadata:
      labels:
        app: learning-portal-frontend
        cluster: learning-development
    spec:
      containers:
        - name: learning-portal-frontend
          image: gograbjob/learning-portal-frontend:10.0.0.1
          ports:
            - containerPort: 3030
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 3030
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3030
            initialDelaySeconds: 5
            periodSeconds: 5

