apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-portal-frontend
  namespace: frontend-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-portal-frontend
  template:
    metadata:
      labels:
        app: learning-portal-frontend
    spec:
      containers:
      - name: learning-portal-frontend
        image: ghcr.io/prod-b2b-ggj-platform/learning-portal-frontend:10.0.0.1
        ports:
        - containerPort: 3025
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
