apiVersion: v1
kind: Service
metadata:
  name: learning-portal-frontend
  namespace: learning-development
  labels:
    app: learning-portal-frontend
    cluster: learning-development
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
      name: http
  selector:
    app: learning-portal-frontend

